### PR TITLE
Updated dependencies to latest.

### PR DESCRIPTION
**Pull request by nagapavan**
Fixed test cases to address dependency update

### CODE REVIEW

**Comment by rishson** [comment]
@nagapavan are you wanting to merge these changes into your own fork of this repo instead?

**Comment by nagapavan** [comment]
@rishson I am trying to merge changes to this repo. For some reason build is failing at `sidekick` evaluation, I was trying to debug. If possible, can you or one of the team help me with merging the changes?

**Comment by rishson** [comment]
@nagapavan thanks for your interest in sidekick. 

Typically, for this project, the process is:
- raise an issue
- discuss the issue
- work through accepting the PR

Is this how you have worked with other projects?

**Comment by nagapavan** [comment]
@rishson 
My apologies for rushing and not following the process.
Yes, I did follow the process in other project. Somehow I got distracted and directly jumped to the PR.

Closing this thread to start-off cleanly.
My apologies once again.

**Pull request closed without merging**
